# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.8.1"

      - name: Get Version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/^v//')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install --loglevel=info --no-save @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: npx semantic-release
